## Name - HARSHIT BHARDWAJ

## TASK- 1  

## Predict the percentage of an student based on the no. of study hours

## Using Linear Regression - Supervised Machine Learning Algorithm

### IMPORT LIBRARIES

In [1]:
import pandas as pd

## LOAD DATASET

In [2]:
path = r"http://bit.ly/w-data"
df = pd.read_csv(path)

In [3]:
df.head()

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

In [4]:
df.tail()

Hours  Scores
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86

## SPLIT DATA

In [23]:
X = df.iloc[:, :-1].values
y = df.iloc[:,1].values

print("Value of X: ",X)
print("value of y: ",y)

Value of X:  [[2.5]
 [5.1]
 [3.2]
 [8.5]
 [3.5]
 [1.5]
 [9.2]
 [5.5]
 [8.3]
 [2.7]
 [7.7]
 [5.9]
 [4.5]
 [3.3]
 [1.1]
 [8.9]
 [2.5]
 [1.9]
 [6.1]
 [7.4]
 [2.7]
 [4.8]
 [3.8]
 [6.9]
 [7.8]]
value of y:  [21 47 27 75 30 20 88 60 81 25 85 62 41 42 17 95 30 24 67 69 30 54 35 76
 86]


## USING SKLEARN TO SPLIT DATA IN TRAIN AND TEST DATA

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state=0)

print("Shape of X_train: ",X_train.shape)
print("Shape of X_test: ",X_test.shape)
print("Shape of y_train: ",y_train.shape)
print("Shape of y_test: ",y_test.shape)

Shape of X_train:  (20, 1)
Shape of X_test:  (5, 1)
Shape of y_train:  (20,)
Shape of y_test:  (5,)


## NOW WE TRAIN OUR ML MODEL

In [25]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

lr.fit(X_train, y_train)

LinearRegression()

## PREDICT THE VALUE OF SCORE

In [26]:
print(X_test)

[[1.5]
 [3.2]
 [7.4]
 [2.5]
 [5.9]]


In [27]:
y_pred = lr.predict(X_test)
print("-------------PREDICTION COMPLETE-------------")

-------------PREDICTION COMPLETE-------------


## NOW WE COMPARE OUR PREDICTED VALUES WITH GIVEN(OR Y_TEST) VALUES

In [28]:
print(y_test)

[20 27 69 30 62]


In [29]:
print(y_pred)

[16.88414476 33.73226078 75.357018   26.79480124 60.49103328]


## NOW WE CAN DO ANY PREDICTION WITH OUR OWN DATA

In [30]:
given_hour = [[9.25]]
resultant_pred = lr.predict(given_hour)
print("No of Hours = {}".format(given_hour))
print("Predicted Score = {}".format(resultant_pred[0]))

No of Hours = [[9.25]]
Predicted Score = 93.69173248737539


### **Evaluating the model**

In [31]:
from sklearn.metrics import mean_squared_error
import numpy as np
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

print("MSE: ",mse)
print("RMSE: ",rmse)

MSE:  21.598769307217456
RMSE:  4.647447612100373
